### ISSUE TITLE
Overloaded class Warning from enforce_element_constraints

### ISSUE THREAD

**Issue by ddundo** [pyroteus/pyroteus#114] opened 2023-02-25 12:40 UTC
Following #91. Function `metric.enforce_element_constraints` raises a Warning

```
/home/ubuntu/software/firedrake-adapt/src/firedrake/firedrake/adjoint/function.py:129: UserWarning: Could not find overloaded class of type '<class 'int'>'.
  other = create_overloaded_object(other)`
```

**Comment by jwallwork23** [comment] 2023-02-28 08:51
@ddundo Please could you provide a snippet of code that would reproduce this warning?

**Comment by jwallwork23** [comment] 2023-02-28 17:27
@ddundo It's because the lists of values for `h_max` and `a_max` get used to assign to `Function`s. Firedrake `Function`s don't like being assigned integer values. Instead, you should make sure you are using floats:
```
metric_enf = enforce_element_constraints(metric, [1e-2], [10.0], [5.0])[-1]
```

This makes the warning go away for me, so I'm going to close this issue.

**Closed by jwallwork23** 2023-02-28 17:27 UTC
Labels: bug
